name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install build tools and dependencies
      run: sudo apt-get update && sudo apt-get install -y g++ libcurl4-openssl-dev

    - name: Build and run
      run: |
        g++ -o myprogram main.cpp -lcurl
        ./myprogram
