name: C++ Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up C++ environment
      uses: actions/setup-cpp@v2
      with:
        compiler: 'gcc'

    - name: Build and run
      run: |
        g++ main.cpp -o executable_name
        ./executable_name
